/**
 * Mock / demo data used when API keys are not configured.
 * Replace with live API calls once keys are set in .env.local
 */

import type { Match, NewsArticle, Standing, Sport } from "@/lib/types";

export const MOCK_LIVE_MATCHES: Match[] = [
  {
    id: 1,
    utcDate: new Date().toISOString(),
    status: "IN_PLAY",
    minute: 67,
    homeTeam: { id: 57, name: "Arsenal", shortName: "ARS" },
    awayTeam: { id: 61, name: "Chelsea", shortName: "CHE" },
    score: { home: 2, away: 1 },
    competition: { id: 2021, name: "Premier League", code: "PL", country: "England" },
    venue: "Emirates Stadium",
  },
  {
    id: 2,
    utcDate: new Date().toISOString(),
    status: "IN_PLAY",
    minute: 34,
    homeTeam: { id: 86, name: "Real Madrid", shortName: "RMA" },
    awayTeam: { id: 81, name: "FC Barcelona", shortName: "BAR" },
    score: { home: 1, away: 1 },
    competition: { id: 2014, name: "La Liga", code: "PD", country: "Spain" },
    venue: "Santiago Bernabéu",
  },
  {
    id: 3,
    utcDate: new Date().toISOString(),
    status: "IN_PLAY",
    minute: 82,
    homeTeam: { id: 5, name: "Bayern Munich", shortName: "FCB" },
    awayTeam: { id: 4, name: "Borussia Dortmund", shortName: "BVB" },
    score: { home: 3, away: 0 },
    competition: { id: 2002, name: "Bundesliga", code: "BL1", country: "Germany" },
    venue: "Allianz Arena",
  },
  {
    id: 4,
    utcDate: new Date().toISOString(),
    status: "PAUSED",
    minute: 45,
    homeTeam: { id: 98, name: "AC Milan", shortName: "MIL" },
    awayTeam: { id: 109, name: "Juventus", shortName: "JUV" },
    score: { home: 0, away: 0 },
    competition: { id: 2019, name: "Serie A", code: "SA", country: "Italy" },
    venue: "San Siro",
  },
];

export const MOCK_UPCOMING_MATCHES: Match[] = [
  {
    id: 5,
    utcDate: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeam: { id: 64, name: "Liverpool", shortName: "LIV" },
    awayTeam: { id: 65, name: "Manchester City", shortName: "MCI" },
    score: { home: null, away: null },
    competition: { id: 2021, name: "Premier League", code: "PL", country: "England" },
    venue: "Anfield",
  },
  {
    id: 6,
    utcDate: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeam: { id: 1, name: "Paris Saint-Germain", shortName: "PSG" },
    awayTeam: { id: 17, name: "AS Monaco", shortName: "MON" },
    score: { home: null, away: null },
    competition: { id: 2015, name: "Ligue 1", code: "FL1", country: "France" },
    venue: "Parc des Princes",
  },
  {
    id: 7,
    utcDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeam: { id: 18, name: "Atlético Madrid", shortName: "ATM" },
    awayTeam: { id: 559, name: "Sevilla FC", shortName: "SEV" },
    score: { home: null, away: null },
    competition: { id: 2014, name: "La Liga", code: "PD", country: "Spain" },
    venue: "Wanda Metropolitano",
  },
  {
    id: 8,
    utcDate: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeam: { id: 66, name: "Manchester United", shortName: "MUN" },
    awayTeam: { id: 58, name: "Aston Villa", shortName: "AVL" },
    score: { home: null, away: null },
    competition: { id: 2021, name: "Premier League", code: "PL", country: "England" },
    venue: "Old Trafford",
  },
];

export const MOCK_STANDINGS: Standing[] = [
  { position: 1, team: { id: 64, name: "Liverpool", shortName: "LIV" }, playedGames: 28, won: 20, draw: 5, lost: 3, points: 65, goalsFor: 68, goalsAgainst: 28, goalDifference: 40 },
  { position: 2, team: { id: 65, name: "Manchester City", shortName: "MCI" }, playedGames: 28, won: 19, draw: 4, lost: 5, points: 61, goalsFor: 62, goalsAgainst: 35, goalDifference: 27 },
  { position: 3, team: { id: 57, name: "Arsenal", shortName: "ARS" }, playedGames: 28, won: 17, draw: 6, lost: 5, points: 57, goalsFor: 58, goalsAgainst: 30, goalDifference: 28 },
  { position: 4, team: { id: 73, name: "Tottenham Hotspur", shortName: "TOT" }, playedGames: 28, won: 15, draw: 5, lost: 8, points: 50, goalsFor: 52, goalsAgainst: 45, goalDifference: 7 },
  { position: 5, team: { id: 61, name: "Chelsea", shortName: "CHE" }, playedGames: 28, won: 14, draw: 7, lost: 7, points: 49, goalsFor: 55, goalsAgainst: 41, goalDifference: 14 },
  { position: 6, team: { id: 66, name: "Manchester United", shortName: "MUN" }, playedGames: 28, won: 13, draw: 5, lost: 10, points: 44, goalsFor: 40, goalsAgainst: 42, goalDifference: -2 },
  { position: 7, team: { id: 397, name: "Newcastle United", shortName: "NEW" }, playedGames: 28, won: 12, draw: 7, lost: 9, points: 43, goalsFor: 44, goalsAgainst: 38, goalDifference: 6 },
  { position: 8, team: { id: 58, name: "Aston Villa", shortName: "AVL" }, playedGames: 28, won: 11, draw: 8, lost: 9, points: 41, goalsFor: 48, goalsAgainst: 44, goalDifference: 4 },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: "1",
    title: "Arsenal Edge Chelsea in Pulsating North London Rivalry",
    excerpt: "A second-half blitz from Arsenal saw them claim a vital three points in a fiercely contested Premier League clash at the Emirates.",
    imageUrl: "https://picsum.photos/seed/football1/800/450",
    category: "football",
    publishedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    author: "James Mitchell",
    source: "GoalPulse",
    slug: "arsenal-edge-chelsea-premier-league",
    readTime: 4,
    featured: true,
  },
  {
    id: "2",
    title: "El Clásico Ends All Square: Madrid and Barcelona Share the Spoils",
    excerpt: "In a tactical masterclass at the Bernabéu, Real Madrid and FC Barcelona played out a thrilling 1-1 draw with late drama on both sides.",
    imageUrl: "https://picsum.photos/seed/football2/800/450",
    category: "football",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    author: "Carlos Vega",
    source: "GoalPulse",
    slug: "el-clasico-1-1-draw-bernabeu",
    readTime: 5,
    featured: true,
  },
  {
    id: "3",
    title: "LeBron James Posts 40-Point Triple-Double as Lakers Rally Late",
    excerpt: "An extraordinary individual performance from LeBron James single-handedly rescued the Lakers in the dying minutes against the Celtics.",
    imageUrl: "https://picsum.photos/seed/basketball1/800/450",
    category: "basketball",
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    author: "DeShawn Brooks",
    source: "GoalPulse",
    slug: "lebron-40pt-triple-double-lakers",
    readTime: 3,
    featured: false,
  },
  {
    id: "4",
    title: "Djokovic Wins Melbourne Thriller in Five Epic Sets",
    excerpt: "Novak Djokovic showed nerves of steel to overcome a tenacious opponent across five sets in an Australian Open semifinal classic.",
    imageUrl: "https://picsum.photos/seed/tennis1/800/450",
    category: "tennis",
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    author: "Sophie Turner",
    source: "GoalPulse",
    slug: "djokovic-melbourne-five-set-thriller",
    readTime: 4,
    featured: false,
  },
  {
    id: "5",
    title: "India Dominate England in Edgbaston Test — Series Lead Secured",
    excerpt: "A dominant India side pressed their advantage at Edgbaston as their pace attack dismantled England's middle order on day three.",
    imageUrl: "https://picsum.photos/seed/cricket1/800/450",
    category: "cricket",
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    author: "Ravi Sharma",
    source: "GoalPulse",
    slug: "india-dominate-england-edgbaston-test",
    readTime: 6,
    featured: false,
  },
  {
    id: "6",
    title: "Bayern Munich Continue Bundesliga Dominance with 3-0 Demolition",
    excerpt: "Bayern Munich extended their lead at the top of the Bundesliga with a commanding win over Dortmund in the Der Klassiker.",
    imageUrl: "https://picsum.photos/seed/football3/800/450",
    category: "football",
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    author: "Hans Mueller",
    source: "GoalPulse",
    slug: "bayern-munich-3-0-bundesliga",
    readTime: 3,
    featured: false,
  },
];

export const MOCK_SPORTS: Sport[] = [
  {
    id: "football",
    name: "Football",
    category: "football",
    icon: "⚽",
    color: "#00C8FF",
    description: "The world's most popular sport with top leagues from around the globe.",
    activeLeagues: 24,
    liveMatches: 12,
  },
  {
    id: "cricket",
    name: "Cricket",
    category: "cricket",
    icon: "🏏",
    color: "#22C55E",
    description: "Test matches, ODIs, and T20s from international and domestic competitions.",
    activeLeagues: 8,
    liveMatches: 3,
  },
  {
    id: "basketball",
    name: "Basketball",
    category: "basketball",
    icon: "🏀",
    color: "#F97316",
    description: "NBA, EuroLeague, and international basketball action.",
    activeLeagues: 6,
    liveMatches: 4,
  },
  {
    id: "tennis",
    name: "Tennis",
    category: "tennis",
    icon: "🎾",
    color: "#A855F7",
    description: "Grand Slams, ATP, WTA, and Davis Cup live scores and results.",
    activeLeagues: 4,
    liveMatches: 8,
  },
];
